name: "Deploy to github pages"

on:
  push:
    branches:
      - "main"
      - "development"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: "automate gitflow"
        uses: Logerfo/gitflow-action@0.0.5
        with:
          github-token: ${{ secrets.TOKEN }} # The `GITHUB_TOKEN` secret.
          release: release # The `release` branch.
          release-regex: ^release/(.*) # The regex for `release` branch.
          dev: developer # The `dev` branch.
          master: main # The `master` branch.
          label: gitflow # The pull request label.
          auto-merge: true
          require-merge: false

      - name: "Checkout"
        uses: "actions/checkout@v1"

      - name: "install and build"
        run: npm install && npm run build

      - name: "deploy"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: development #put the branch you want to deploy
          folder: build # The folder the action should deploy.